# Inference configuration for retail forecasting

# environment configuration
settings:
  docker:
    target_repository: zenml-ml-forecast
    allow_download_from_code_repository: True
# configuration of the Model Control Plane
model:
  name: retail_forecast_model
  version: 0.1.0
  license: MIT
  description: A retail forecast model for inference
  tags: ["retail", "forecasting", "prophet", "inference"]

# Step-specific parameters
steps:
  # Data loading parameters
  load_data:
    # No specific parameters needed for this step
  
  # Data preprocessing parameters
  preprocess_data:
    test_size: 0.05  # Small test set for visualization only
  
  # Forecasting parameters
  generate_forecasts:
    forecast_periods: 30 