# Training configuration for retail forecasting

# environment configuration
settings:
  docker:
    target_repository: zenml-ml-forecast
    allow_download_from_code_repository: True
    pyproject_path: pyproject.toml
    build_config:
      build_options:
        platform: linux/amd64

# configuration of the Model Control Plane
model:
  name: retail_forecast_model
  version: 0.1.0
  license: MIT
  description: A retail forecast model with enhanced seasonality
  tags: ["retail", "forecasting", "prophet", "seasonal"]

# Step-specific parameters
steps:
  # Data preprocessing parameters
  preprocess_data:
    test_size: 0.15
  
  # Model training parameters
  train_model:
    weekly_seasonality: true
    yearly_seasonality: true
    daily_seasonality: true
    seasonality_mode: "additive"
  
  # Forecasting parameters
  generate_forecasts:
    forecast_periods: 60 